[[MPC]]
arch = "aarch64"
git-tree-sha1 = "ddfbd0f9b83dd1533f2a15fd768502d10798b591"
os = "macos"

    [[MPC.download]]
    sha256 = "dde5d88113f00b58f9dda4aaab77d2127b978b795757c48706946b81f758f6d5"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.aarch64-apple-darwin.tar.gz"
[[MPC]]
arch = "aarch64"
git-tree-sha1 = "02c2792ca17698e1503d9368c4cbf4fc6fde5e99"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "3b5bc35bd504da425d4f53a14cf7eb3bd900cefa2553e66cda522e385ab70203"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.aarch64-linux-gnu.tar.gz"
[[MPC]]
arch = "aarch64"
git-tree-sha1 = "a454f067c51733e22e8969821ee3f34adb998671"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "032fffc73a0f502d56fab1003dbbe4d82f9948a0a286c42ce33eda8e4e68d78b"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.aarch64-linux-musl.tar.gz"
[[MPC]]
arch = "aarch64"
git-tree-sha1 = "ff7be223628b10be6ef51dd4da471fcd2f99e2c2"
os = "freebsd"

    [[MPC.download]]
    sha256 = "5b47655f2703aa1ee8917161093aba06416079559a544be178121d68dd6d2dff"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.aarch64-unknown-freebsd.tar.gz"
[[MPC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "768ec56f227afbc4b8806761cca2721811c3082f"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "d823b73b7d313ab03641d9e7775f97099b8d7203d784cb4e77b670a53d9d2212"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.armv6l-linux-gnueabihf.tar.gz"
[[MPC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7564ff84227593df428096c04dcfe50286f42283"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "16df2143161c384230258440ca70a450f0af616d2375e9968c90703f84c8696a"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.armv6l-linux-musleabihf.tar.gz"
[[MPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fb2a9f0ec82717ca5d876f62102bdc29a7fc0b9a"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "1882b87e4f9f4cc1527881d156852ac6daba875007f03ed9ffa2eba9c4ffc4e8"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.armv7l-linux-gnueabihf.tar.gz"
[[MPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a0161fd4264abc3fbacb9359cbb6e2cf0e089ace"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "1629044609f0410a39b52783cf2dbe8051c23072deb0189b93d063bfa39d29df"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.armv7l-linux-musleabihf.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "09de4110c8a27999ec75800f8b601a06c0e2409e"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "5b1353c69119254e62d391ff9ff5c75fecff0c0d068d1d64eb21096de55e9476"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.i686-linux-gnu.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "eb61d602891aa3b443115bc124d9fca7a5781823"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "5967f405618978d8d615189431035dd30f43330b10a361effae792948e0b151e"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.i686-linux-musl.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "40825748e33385776daa465ebd20e22f0fc322df"
os = "windows"

    [[MPC.download]]
    sha256 = "0fda96604b8e8997b11dc4a54de4c9154427d387bf871e54604f49313a6b25f9"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.i686-w64-mingw32.tar.gz"
[[MPC]]
arch = "powerpc64le"
git-tree-sha1 = "127dd3ad0e42fd3a14748892b3947b3a7f21f98c"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "9373a5fbdb7efb307afd3f6cf1b582417d8151ff551fbd03666bb3348bdbe311"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.powerpc64le-linux-gnu.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "21b15da0497846ef3d0ab16f55830b63f1fd9838"
os = "macos"

    [[MPC.download]]
    sha256 = "b8cda8f9d544a270e7e1a9e0e71e542450194792c5b4ddf81e8cfd6fe0da8f8d"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.x86_64-apple-darwin.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "b75762db34a0b8cf51d0e546649dbb5d76765354"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "fb07512b05eeaa90b60af4786b08261c78f4c25653998b138d1e018f9e3b282e"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.x86_64-linux-gnu.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "685096160c2cade3221a26fbd1baa0eecb8e12e9"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "543d09f850b72422050540e15a8c08daa8a1f35e937888ba59c93379629c1d6e"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.x86_64-linux-musl.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "0d83b67fff90eabb7cf13518f3e641ffd6e0220e"
os = "freebsd"

    [[MPC.download]]
    sha256 = "112a00568ada8787dae1281b11bfd703736bfbfbc97ad0b0770ca91b4a1d9827"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.x86_64-unknown-freebsd.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "c17fa75503bd259d6670c6c91bdf0e07aafcc568"
os = "windows"

    [[MPC.download]]
    sha256 = "949a23b35c20e72f4d555fe9891105ba7f4071740959d17df3e86a7a65f68665"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.3.1+0/MPC.v1.3.1.x86_64-w64-mingw32.tar.gz"
