[[MPC]]
arch = "aarch64"
git-tree-sha1 = "9e329d200c95eacacc7c6368c2db48c32efecc31"
os = "macos"

    [[MPC.download]]
    sha256 = "a8afa33d4e8504bab0ef49275d67065f21e5aef119c8506025a560bdcfdb08f3"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.aarch64-apple-darwin.tar.gz"
[[MPC]]
arch = "aarch64"
git-tree-sha1 = "ef5bf40f1cbb41477e66601bef5491d7a8e1996f"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "0444f3a4189298e1c646e984ca3152f5726a269baba77ef3df2c2be3c2bf6f1d"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.aarch64-linux-gnu.tar.gz"
[[MPC]]
arch = "aarch64"
git-tree-sha1 = "9a4080cbc7d6305f0460e93eb9ae7a72abe22d07"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "7980c3d63e81a2d9fb2023409e8d0518e86aac265d4796ba4f04d56774b5fdab"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.aarch64-linux-musl.tar.gz"
[[MPC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8b83f7d0d4f3706976d2147454cf673254c5b76f"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "8a4db5df250a6eb2c38ef6c37d0639fbe77488395a330f61092734ba456211bf"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.armv6l-linux-gnueabihf.tar.gz"
[[MPC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "55af257f1f26136ad3cd9428492e56e21948faa0"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "4727be5f6947de1db1b33838bb876a077d66673e9289d94eecd08d415c82b775"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.armv6l-linux-musleabihf.tar.gz"
[[MPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1aa87b7f161ff0e73a44880c8f73922759722edf"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "feff4e5600f7e3030a430b85efdc3ebc18e69f0599e8603d0346e96d31795c8b"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.armv7l-linux-gnueabihf.tar.gz"
[[MPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fb2b1d0773aeb01b06b10fa42789c1d5f90fb7e9"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "81bb5785af2e69068aaafb4d49c0950f5a15cedc7773474ee4f4a2554c40c148"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.armv7l-linux-musleabihf.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "e6c9e3e81b72807d7a0ffe5710c1fdb0f00f88de"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "5305d6e1a4826d74f00c9e6a6fb0d73ea39548bec39c46a59896693da089896e"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.i686-linux-gnu.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "ab254f715c5c94ff260f0a8f9ad846762985f368"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "694745b552f728c116da1bed121a5c21f74340f1b965f411efe18ed167dcd065"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.i686-linux-musl.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "4e0646d2590e34fd440cde0422046b38de5ba06c"
os = "windows"

    [[MPC.download]]
    sha256 = "ad61cad4e91764d949dc980d4b5a00f1668ba6f7e131718b9f844ea1935bcb70"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.i686-w64-mingw32.tar.gz"
[[MPC]]
arch = "powerpc64le"
git-tree-sha1 = "0908d6feaffa862a1ac9017a8b8aac42b790da29"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "8f5638b490196caf2f0d7d667b0b6779a8fc245b6f3b46ecb5bdee2cd62abe63"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.powerpc64le-linux-gnu.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "d2ccdf320608d26f357e7b5da32f6e0448a84ac6"
os = "macos"

    [[MPC.download]]
    sha256 = "541ff3dd3364477ff3ba725a02e590690c76d8d81ac62c14e7382a5e6ca68417"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.x86_64-apple-darwin.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "576d0dbb8081c9f93f59183fdfa3855c5702e616"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "40fabdd7a191edb2a8a1080bac31b51718d444d1fceea60351f3f17fbedc59d1"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.x86_64-linux-gnu.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "56cfec1ba6eaa0af4090fcbe659ce6346a4c125e"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "541e616da7518bd5c1f693419ff390d7492c2a694b32a097afab9678b9274901"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.x86_64-linux-musl.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "8e93f7cb70026c012366633fc87430c7491df19d"
os = "freebsd"

    [[MPC.download]]
    sha256 = "87cfa76b0f82fa5fd314caa81eb80119208928ed550115d32f5ba5c8f2a7ef03"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.x86_64-unknown-freebsd.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "bb4602c7928116613fbef0a63eb5dfb27fd9b703"
os = "windows"

    [[MPC.download]]
    sha256 = "597bd07842e14ac9100a581bc3922d53f0d1fe6834f8371b4b2ad9000f20be85"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.2.1+0/MPC.v1.2.1.x86_64-w64-mingw32.tar.gz"
